### ISSUE TITLE
如果支持查看沙盒里面的文件 可以实时看sqlite就更太好了

### ISSUE THREAD

**Issue by phpmaple** [blankapp/flutter_flipperkit_plugins#3]

**Comment by lijy91** [comment]
当前可能通过 [flipperkit_sqflite_driver](https://github.com/blankapp/flutter_flipperkit_plugins/tree/master/packages/flipperkit_sqflite_driver) 查看指定的 sqlite 数据库，沙盒文件这个功能我做一下调研。

**Comment by lijy91** [comment]
I am developing [AnyInspect](https://github.com/anyinspect/anyinspect_app) to replace Flipper, `flutter_flipperkit` will stop updating in the near future.

[![Discord](https://img.shields.io/badge/discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)](https://discord.gg/X2Gcce3Q)
