### ISSUE TITLE
Driver for get_storage or hive?

### ISSUE THREAD

**Issue by qbait** [blankapp/flutter_flipperkit_plugins#6]
By any chance, do you have an interest in writing the driver for `get_storage` or `hive`?
https://pub.dev/packages/get_storage
https://pub.dev/packages/hive

**Comment by lijy91** [comment]
I am developing [AnyInspect](https://github.com/anyinspect/anyinspect_app) to replace Flipper, `flutter_flipperkit` will stop updating in the near future.

[![Discord](https://img.shields.io/badge/discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)](https://discord.gg/X2Gcce3Q)
